addons:
  apt:
    packages:
    - libsofia-sip-ua-dev 
    - libcunit1-dev
    - check
cache:
  directories:
  - $HOME/sofiasip
language: c
compiler: gcc
before_install:
  - bash install-sofiasip.
script: 
  -  ls -R $HOME/sofiasip
  - ./autogen.sh && ./configure && make
